### ISSUE TITLE
[CLI] Generate RBAC resources for tenant

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops-enterprise#1002]
This story is about generating the correct RBAC resources for the tenant. (Role + Rolebinding ). Completing the RBAC resource creation should unlock:

- As a Platform Operator, I want to define and restrict what types/kinds can be deployed by my Application Developers so that I can control what gets reconciled

- As Platform Operator, I can set roles within a tenant/workspace for my application developers and bind them to my OIDC Usergroups so that I can granular control my user RBAC inside a tenant/workspace (User RBAC)

- As Platform Operator, I can set role for the service account within a tenant/workspace and bind them to my OIDC Usergroups so that I can granular control my deployment RBAC for a tenant/workspace (Deployment RBAC)

**Design**

https://www.notion.so/weaveworks/Multi-tenancy-Technical-Inception-e2f3c2488a4a4c1a838470e1d61e976a

**Tasks**

Create a new gitops CLI command `create tenant –file tenants.yaml` which receives a YAML file including one or more tenant

- [ ] Validate tenants’ YAML format
- [ ] Generate resource objects directly into the cluster for each tenant in the file similarly to `flux create tenant`
- [ ] Check if `export` flag is used and export the generated resources files to the requested destination instead of applyly directly to the cluster
- [ ] Update docs with an example for the expected tenants file
