### ISSUE TITLE
Create Pipeline resource

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#1237]
As a platform operator, I want to create a Pipeline resource that represents the order of environments through which an application gets deployed, so that an application team can view the status of their application for each of those environments.

[Terminology](https://www.notion.so/weaveworks/CD-Pipeline-39a6df44798c4b9fbd140f9d0df1212a)

- [x] weaveworks/corp/issues/2901
- [x] weaveworks/weave-gitops-enterprise#1248
- [x] weaveworks/pipeline-controller#5
- [x] weaveworks/pipeline-controller#4
- [x] weaveworks/weave-gitops-enterprise#1250
