### ISSUE TITLE
[BE] Update GetProfiles / GetProfileValues to work with any HelmRepository CR and on any cluster

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1282]
Motivation: allow a user to select a Chart from a HelmRepository on a leaf cluster install on the leaf cluster.

We currently only support returning the available profiles/helmcharts from a hardcoded HelmRepository (flux-system/weaveworks-charts). We want to allow the user to select any HelmRepository loaded into the cluster. We need to adapt GetProfiles / GetProfileValues so they can accept params in the HTTP request to specify { Name, Namespace }.

The helm-cache-controller only caches profiles in the management cluster. To allow users to list available profiles/helmcharts on leaf clusters it should also scan them for available profiles and save to its cache. Then GetProfiles / GetProfileValues should be updated so it can accept a ClusterName alongside the proposed { Name, Namespace } above.

Split out from #1199

### Tasks

- [x] Make factory.Clusters.Set return the diff (ClustersUpdate{Added: []Cluster, Removed []Cluster})
  - [x] Make factory.Clusters.clusters a set (apimachinery/pkg/utils/sets)
  - [x] Might have to implement a new thing..
- [x] Make the helm-cache cluster aware
- [x] Update the getProfiles/getProfileValues API endpoints to receive clusterName
- [x] Change factory.UpdateClusters to publish new clusters on a "added" channel and removed clusters on a "removed" channel
  - [x] Expose the channels via a public method factory.AddRemoveChannels()
- [ ] Pass the channels into a new MultiHelmWatcher thing
  - [ ] MultiHelmWatcher will construct / teardown HelmWatchers
  - [ ] Some way to get the kubeconfig for the cluster (pass in chan / getter fn)

### Hopefully look kinda like this

![image](https://user-images.githubusercontent.com/22008/184658463-57fd7d06-9b7e-484d-ad25-9d6b27a5cb02.png)
