### ISSUE TITLE
Create new PR for next environment in pipeline

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#1589]
As a application engineer, when a successful deployment of a new version of a Helm release is detected in an environment of my pipeline, I want a new PR to be automatically created  for the next environment in my pipeline that updates it to the same version, so that my team can review it.

- [x] weaveworks/weave-gitops-enterprise#1592
- [x] weaveworks/pipeline-controller#30
- [x] weaveworks/pipeline-controller#31
- [x] weaveworks/pipeline-controller#33
- [x] weaveworks/weave-gitops-enterprise#1598
- [x] weaveworks/weave-gitops-enterprise#1599
- [x] weaveworks/pipeline-controller#32

Notes:
- Need to provide configuration to determine whether we want to create a PR upon an event or after all targets in an environment get updated. By default a promotion starts when an event is received regardless of the number of targets in an environment.
- How do we know what to update in Git? An approach could be to follow what the ImageAutomationController does by putting a placeholder comment. This should come from the Pipeline CRD.
- Need a sample scenario to use for discussion and a sample repo too. We can collaborate on the Notion doc ([link])(https://www.notion.so/weaveworks/Pipeline-promotion-061bb790e2e345cbab09370076ff3258)
- Sequence diagram for end to end solution, what responsibilities are in which components

Restrictions / Assumptions:
- All Helm Release objects for deployment targets within an environment must exist within the same repository. So that we can create a single PR to update the environment.

References 
- [Pipeline promotion product initiative](https://www.notion.so/weaveworks/Pipeline-promotion-061bb790e2e345cbab09370076ff3258)
