### ISSUE TITLE
[BE] Add pricing data fetcher for AWS

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1681]
Lots of great AWS Pricing API exploration [here](https://gist.github.com/bigkevmcd/6f6409b8acbfc54f9e37e51c0dc1d45f).

### Task breakdown

- [ ] ~Update the helm-chart/clusters-service/deployment.yaml to optionally mount a k8s secret `pricing-api-credentials` onto the clusters-service.~
  - ~`PRICING_API_AWS_ACCESS_KEY_ID` / `PRICING_API_AWS_SECRET_ACCESS_KEY`~
  - Instances will have IAM permissions do the queries. For testing locally you might have to add `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`.
- [ ] Allow use to configure the queryParams we'll use to query the pricing API via the helm chart[0]
- [ ] Query the pricing data on cluster-service startup and hold it in memory / write to disk

[0]
```yaml
config:
  costEstimation:
    aws:
      queryParams: "operatingSystem=Linux&regionCode=us-east-1"
```

Questions:
- Is this true?: We don't want to expose the existence of this feature to anyone poking around our apis / helm-chart / deployment.yaml etc.
