### ISSUE TITLE
[BE,DT] As a User, I want to connect my clusters to the hub using OIDC endpoint instead of a Kubeconfig

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops-enterprise#1886]
### Background

We have a customer that will use instead of a Kubeconfig an API endpoint and a CA to obtain the token and construct the rest client to access the cluster. 
This means that we need to enable a passthrough method for our GitOpsCluster so that the spokes can connect via this method to the hub. 
This particular request is from DT which is implementing WGE as a single pane of glass across their fleet of clusters and tenants.

Currently, the way we fetch namespaces relies on a secret/kubeconfig this won't work with the passthrough method. This is a blocker, and we need to look for alternatives.
[
Technical doc outlining problem and approaches.](https://gist.github.com/bigkevmcd/70969910b283c1382c2a555fafa4ae59)

### Goal
**As a User, I want to connect my clusters to the hub using OIDC endpoint instead of a Kubeconfig**

User can provide an API endpoint and CA authority to connect to a cluster. 

Extracted from Kevin's doc:

```

apiVersion: v1
kind: Secret
metadata:
  name: kube-server-secret
  namespace: clusters
stringData:
  certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHV
  server: https://127.0.0.1:12906
```

### Tasks

- [ ] Change how we're building the restconfig for the client https://github.com/weaveworks/weave-gitops-enterprise/blob/main/pkg/cluster/fetcher/gitopscluster.go#L163 , if passthrough enabled perhaps grab a diff key from the kubeconfig
- [ ] Make sure we're refreshing OIDC tokens properly
- [ ] IF passthrough is enabled then the namespace-caching thing will be behave differently, and won't be able to build the complete list of namespaces "in the background" anymore.
