### ISSUE TITLE
Migrate code in OSS only referenced by WGE project

### ISSUE THREAD

**Issue by antonyquant123** [weaveworks/weave-gitops-enterprise#2086]
- [ ] moving all the git auth code out of OSS and into EE

- [ ] We've chatted about pulling common code for UI out into a ui-lib (should have some notes on this one somewhere)
- [ ]  We've chatted about pulling out common BE code into some pkg repo too (prolly doc for this too)
- [ ] 		MC querying

[https://docs.google.com/document/d/1723rIShEsXLYotkA1q3OfB76cnYAl1OGzxAuM7W68Pw/edit?usp=sharing](url)
