### ISSUE TITLE
Pipelines - Manual Promotion 0.2

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#2105]
Link to initiative: https://www.notion.so/weaveworks/Manual-Promotions-6270cddd363648e08c259e671063aadf
Designs: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=4717%3A5709&t=bhtG5OGB3ZFiLH49-0

This fast-follow milestone is to cover basic observability concerns and to support the highly-likely user scenario where a manual promotion is only required on a subset of environments.

Acceptance criteria:
- [ ] As a user, I can navigate to an events tab on a given Pipeline to discover historical progress and troubleshoot issues
- [ ] As a user, I can discover the basic status of my Application Pipeline through logged events, as an example this could include : new version being detected, promotion available, promotion requested, promotion complete. 
- [ ] As a user, I should be able to diagnose where in a pull request promotion the process has failed, i.e. failed to clone repo, failed to commit, failed to raise pull request.
- [ ] As a user, when a promotion has been requested (manually / automatically), I am presented with visual feedback which shows me whether the pull request or notification has successfully been created or an error has occurred with the ability to discover details of the error from within the UI.
- [ ] As a user of Pipelines where the pull request strategy has been chosen, when a pull request is generated whilst I am in the Pipelines UI, I am provided with a direct link to the pull request.
- [ ] As a Pipeline author, I can configure my Pipeline so that manual promotion is only required / available between specific environments, i.e. on production only.
- [ ] As a user, I can discover the ability to have manual promotions on a subset of environments within a Pipeline through updated documentation
- [ ] As a user, I can discover the latest capabilities in pipelines through updated documentation including screenshots of the latest UI.
