### ISSUE TITLE
Manual Promotions - 1.0

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#2106]
Link to initiative: https://www.notion.so/weaveworks/Manual-Promotions-6270cddd363648e08c259e671063aadf
Designs: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=4717%3A5709&t=bhtG5OGB3ZFiLH49-0

This Epic is to cover the remaining capabilities for our first major iteration on manual promotions based on known requirements at this stage. It may be further broken down into Epics between 0.2 and 1.0 as appropriate.

Acceptance criteria:
- [ ] As a Platform Administrator, I can appropriately control which users have the ability to manually enact a promotion without requiring elevated privileges on the Pipeline custom resource.
- [ ] As a user I can manually retry promotions which have failed previously
- [ ] As an administrator, I can discover the logged identity of the user who manually requested promotion and the time at which it was requested.
