### ISSUE TITLE
[Spike] Make weaveworks-charts private and setup a CBC config to copy its secret across

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2649]
### Context

We want to support multiple helm-repositories when adding chart ("profiles") when rendering a template e.g. on this page:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/22008/231136379-fb3f301c-422c-4953-95a9-7b10fe4e81a2.png">

- Right now, we only show the profiles that are in this single helmrepo called "flux-system/weaveworks-charts"
- We search for this "flux-system/weaveworks-charts" in the cluster but expect the user to add it themselves, and they can choose what URL it points to etc
- right now we expect it to be public!

### Tasks

- [x] If we use the wge helmrepo to test this, in tilt, update https://github.com/weaveworks/weave-gitops-enterprise/blob/main/tools/dev-resources/user-guide/profiles-helm-repository.yaml to be the actual private WGE helm repo mentioned in the user-guide[0]
- [x] We need to add a https://github.com/weaveworks/cluster-bootstrap-controller#secretsync `SecretSync` to copy across the secret for the private helm repo to the new leaf cluster ( secret: `flux-system/weave-gitops-enterprise-credentials`), it should probably have a similar label selector to the CBC config:

```yaml
  clusterSelector:
    matchLabels:
      weave.works/capi: bootstrap
```

- [x] Seems like we copy the spec from the management cluster and write it out to the PR, so don't think we have to do anything else here wrt to injecting the secretref etc. https://github.com/weaveworks/weave-gitops-enterprise/blob/f84d5b28906a436b5230f938c9838d163988e4a2/cmd/clusters-service/pkg/server/templates.go#L431

### notes

- New CBC supports copy secrets
- Add a private helmrepo w/ a secret called `flux-system/weaveworks-charts`
  - Make sure its auth info is copied across

[0]
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 60m
  secretRef:
    name: weave-gitops-enterprise-credentials
  url: https://charts.dev.wkp.weave.works/releases/charts-v3
```
