### ISSUE TITLE
WGE Observability Phase 3 - V 1.0   - explorer for applications is complete and production ready

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#2808]
**From** https://www.notion.so/weaveworks/Scaling-Weave-Gitops-Observability-Phase-3-7e0a1cfcc89641c9bb05a05c5356af34?pvs=4#d175338bd2004544ac8d52764ce26140

**Description** 

This release builds upon previous to achieve that explorer

- It has a complete and stable set of features that allows users to discover applications.
- It could be safely used in production.

**Acceptance Criteria**

- [ ]  As Explorer user, I have a complete navigation experience regarding previous applications experience by
    - [ ]  parity in terms of required data is shown
      - [x] filters https://github.com/weaveworks/weave-gitops-enterprise/issues/2765
      - [ ] other applications columns https://github.com/weaveworks/weave-gitops-enterprise/issues/2766
      - [ ] status https://github.com/weaveworks/weave-gitops-enterprise/issues/2767
    - [ ]  a complete kube RBAC integration
      - [ ] defined / well-known limitations of the current approach vs the old approach
      - [x] spiked whether we could use rbac from kube https://github.com/weaveworks/weave-gitops-enterprise/issues/2845
      - [x] complete rbac by leveraging kube rbac implementations https://github.com/weaveworks/weave-gitops-enterprise/pull/2882
      - [x] otherwise complete rbac by custom complete implementation (dependency on the previous spike)
    - [ ]  a simple and flexible way to discover or refine applications via text querying
      - [x] #2876
      - [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/2868 
      - [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/2887
    - [ ]  a simple and flexible way to discover or refine applications via non-text querying
      - [ ] update filtering documentation https://github.com/weaveworks/weave-gitops-enterprise/issues/2920
      - [ ] #2877
- [ ]  As a platform operator, I am confident in using Explorer in production as
   - [ ]  I could operate and troubleshoot production issues by leveraging telemetry  
      - [ ] vision: https://github.com/weaveworks/weave-gitops-enterprise/issues/2945 
      - [ ] monitoring query path 
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/2798 
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/3005
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/3006
      - [ ] monitoring collector path
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/2872 
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/3015
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/3003
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/3007
         - https://github.com/weaveworks/weave-gitops-enterprise/issues/3043
      - [ ] SLOs created
      - [ ] logging for request troubleshooting
          - [ ] enable access logs 
          - [ ] generate a requestId at the server so any api request is identified
          - [ ] propagate requestId to explorer requests and document how other services could leverage it for troubleshooting application errors.
          - document debug level for explorer #2878
      - [ ] #2879
   - [ ] Its performance limitations are known as well as its scaling dimensions 
     - [ ] stress test querying service to understand: breaking points, stable performance, and scaling dimensions
     - [ ] stress test collecting path to understand: breaking points, stable performance, and scaling dimensions
   - [ ]  It is tolerant to transient failures and recovers gracefully
     - [ ] Identify the major query path failures modes and ensure there is in place: a graceful handle of the failure 
   and a recovery mechanism in place (for example, cannot read from datastore, or indexing request takes 100secs,  leaf cluster API server connection downtime and data could be stale )
        - consistency on reads https://github.com/weaveworks/weave-gitops-enterprise/pull/3014
        - [x] https://github.com/weaveworks/weave-gitops-interlock/issues/435
     - [ ] Identify the major collecting path failures modes and ensure there is in place: a graceful handle the failure  and a recovery mechanism in place (for example, leaf cluster API server connection downtime and how to a) don't bring down the full collector, b) read delta updates once is back) https://github.com/weaveworks/weave-gitops-enterprise/issues/2804
        - [ ]  consistency on writes https://github.com/weaveworks/weave-gitops-enterprise/pull/2973/files#r1243276418
   - [ ]  threats for users and assets are well known with controls to reduce their exposure
     - [ ] do a simple threat model for querying path with actions to mitigate risks (best practices documentation, rbac, policies, etc ...)
     - [ ] do a simple threat model for collecting paths with actions to mitigate risks (best practices documentation, rbac, policies, etc ...) 
- [ ]  As an existing WGE customer I am able to get its benefits
    - [ ]  SAs
    - [ ]  Pepsi
