### ISSUE TITLE
Weave Gitops single codebase - discovery

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#2930]
This epic for the discovery tasks on the initiative https://www.notion.so/weaveworks/Weave-Gitops-Single-Codebase-Discovery-ecacab647c6049d2845508108c7782c8?pvs=4 

The expectation to close this epic is that we have achieved the following

Scope

- [ ] problem statement has been clearly scoped with both technical and business stakeholders. 
- [ ] technical outcomes have been clearly defined and supported by technical stakeholders.
- [ ] business outcomes have been stated and supported by business stakeholders.
- [ ] a set of alternative solutions has been sketched and agreed to go for discovery with stakeholders.

Discovery:

For each solution to be discovered we expect to understand and backup
- [ ] its technical and business feasibility
- [ ] a poc to proof it 
- [ ] its adoption roadmap 

Deliverable:
- [ ] A summary doc with the previous steps and recommended next steps. 
- [ ] Aligned with stakehodlers

Stakeholders:
- Technical: WW Product Engineering 
- Business: WW Business, CX and Sales

Timelines:
- Scope: first half of June (could slip into the third week of June).
- Discovery: second half of June no later of mid-July.
