### ISSUE TITLE
Weave GitOps with Flux Add-on in AKS Implementation

### ISSUE THREAD

**Issue by lasomethingsomething** [weaveworks/weave-gitops-enterprise#2935]
## What Is Our Goal?
Enable an Azure AKS/Azure Arc customer who has [installed the Azure Flux add-on](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli) to adopt WGE from the Marketplace and join AKS clusters to WGE—enjoying richer k8s deployments and a seamless user experience.

## What Are Our Requirements? (to be broken down further below) 

- [x] We’ve defined step-by-step how an Azure AKS customer who has installed the Azure Flux add-on can adopt WGE from the Marketplace and join AKS clusters to WGE (the integration) (spike to help with this: https://github.com/weaveworks/weave-gitops-enterprise/issues/2937)
- [x] We’ve documented steps, if they're different from Azure, for an Azure Arc customer who has installed the Azure Flux add-on to adopt WGE from the Marketplace and join AKS clusters to WGE (the integration)
- [x] We evaluate our OOTB compatibility with the Azure add-on, Azure UI, and potential integration points which may be served by metadata initiatives, and 
- [x] We’ve integrated Weave GitOps' advanced features, such as cluster fleet management, trusted application delivery, and progressive delivery with AKS and Azure Arc
- [x] MSFT handles ConnectedClusters billing and other matters on their end, and we go live with a coherent solution

## Why Is It Our Goal?
- Currently the steps are an open question
- Need to identify and resolve compatibility issues, blockers, and pain points that could provide a negative experience for users

## Who Will Help Us Achieve the Goal?
- All dev teams have contributed
- David Tesar (MS) eager to do the validation and testing of the image himself
- Others at MSFT (need to follow up)

## Work Plan
- [x] First step: a spike to just try it: https://github.com/weaveworks/weave-gitops-enterprise/issues/2937
- [x] From there, split into:
     - [x] Make changes in WGE as discovered in the above spike;
     - [x] Draft the document require above: “[define] step-by-step how an Azure AKS/Azure Arc customer who has installed the Azure Flux add-on can adopt WGE from the Marketplace and join AKS clusters to WGE.

## Technical Questions, Risks, and Blockers
