### ISSUE TITLE
WGE onboarding: cli bootstrapping

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#3026]
Tracks work for https://www.notion.so/weaveworks/WGE-Onboarding-Day-0-4d35a1660d414663bc5ba053b86b54e6?pvs=4

**Release 1**

- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3507
- [x] #3493
- [x] [BLOCKED] https://github.com/weaveworks/weave-gitops-enterprise/issues/3473
- [x] #3496
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3506
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3420
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3465
- [ ] #3492
- [x] #3494
- [x] #3497
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3508
- [ ] evaluate using go-git over go-scm
- [ ] cluster-user auth should have flag to reuse credentials if they exist
- [x] revisit considering success message as logging event over ouptuts
- [ ] consistent usage of logging and error management across
- [ ] use default 

**Release 2**

- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3295
- [ ] https://github.com/weaveworks/weave-gitops-enterprise/issues/3509
- [ ] https://github.com/weaveworks/weave-gitops-enterprise/issues/3535
- [x] #3619
- [ ] add acceptance tests to auth command 
- [ ] add integration test for git and integration 
- [ ] support scenario where we have difference security context for weave-gitops and flux by namespace

**Release 3** (by December 8th)
- [x] #3495
- [ ] https://github.com/weaveworks/weave-gitops-enterprise/issues/3674
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3276

**Release 4** (till end of year 2023)
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3707
- [ ] #3706
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3496
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3420
- [x] https://github.com/weaveworks/weave-gitops-enterprise/issues/3659
- [ ] security assessment and messages about writes
- [ ] #3618
- [ ] (stretch) refactor flux steps into a single one
- [x] #3709
- [ ] #3715
- [ ] https://github.com/weaveworks/weave-gitops-enterprise/issues/3698
- [ ] fix: if --bootstrap-flux we should not ask user on whether bootstrap flux (independent of --silent) https://weaveworks.slack.com/archives/C05HC9R4DUG/p1702388715145859
- [ ] https://github.com/weaveworks/weave-gitops-enterprise/issues/3713
- [x] #3737

**Others**
- [ ] non-interactive configuration via file instead of flags to simplify non-interactive flows
- [ ] at the end of the bootstrapping session add the non-interactive command or the configuration file to be used for subsequent bootstrap executions.
- [ ] kube, flux and wge version compatibility
- [ ] support write access to git for pull request creation http://localhost:3000/docs/enterprise/getting-started/install-enterprise-getting-started-onboard/#enable-write-access-to-git
