### ISSUE TITLE
[docs] add backstage checklist

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#3060]
All should be working on all tables:
- [x] sorting
- [x] filtering, e.g. can you filter by cluster / sha / etc (other things which might appear in a tooltip / not primary value of a `td`)
- [x] no more "jumping" / flickering
- [x] maybe we should add this to a dev guide / pr-review guide etc? Things to double check when you're adding a new table.
