### ISSUE TITLE
Explorer - V 2.0 - leverage capability beyond applications

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#3093]
[v2.0 iteration](https://www.notion.so/weaveworks/Explorer-Scaling-Weave-GitOps-Observability-Phase-3-7e0a1cfcc89641c9bb05a05c5356af34?pvs=4#cca8ff5618c24dae9abf364fa21267d6)

**Description** 

This release builds upon previous to achieve that explorer could be leverage as platform capability for other kinds beyond application. It should include the possibility to retain resources beyond the current mode of caching. 

**Acceptance Criteria** 

- [ ]  As weave gitops engineer, I could extend explorer in a self-service manner to onboard other non-applications kind:
    - [x]  exists self-service documentation for the extension process (tangerine)
        -  Documentation [here](https://github.com/weaveworks/weave-gitops-enterprise/blob/main/docs/extending-explorer.md)
    - [x]  It includes a simpler process to extend other kinds and generic components for a basic experience, like generic UI (tangerine)
        - TODO: update internal and user documentation
    - [ ]  they have the same production-readiness guarantees as applications (tangerine)
    - [ ]  process validated with a kind that does not require persistence like https://github.com/weaveworks/weave-gitops-enterprise/issues/2957 (pesto?)
- [ ]  As weave gitops engineer, I could onboard kind with persistence needs
    - [ ]  explorer supports persistence associated with kinds via configuration (tangerine)
        - https://github.com/weaveworks/weave-gitops-private/blob/main/docs/adrs/0019-query-retention.md
        - https://github.com/weaveworks/weave-gitops-enterprise/pull/2968
        - TODO: update internal and user documentation
    - [ ]  persistence meets production-readiness guarantees (tangerine)
    - [ ]  policy violations are onboarded to explorer with retention beyond 24hs (timberwolf)
         - TODO: Tiimberwolf to refine the basic experience until complete the AC here https://github.com/weaveworks/weave-gitops-enterprise/issues/2936
