### ISSUE TITLE
The `cluster-reflector-controller`

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#3387]
https://gist.github.com/bigkevmcd/a38631d5148b1f8e8f3939aaa82aaf8f#relevant-code

Tasks

1. [ ] Create a new repository `cluster-reflector-controller`
2. [ ] Run `kubebuilder` etc to bootstrap a new controller
3. [ ] Figure out how to talk to Azure and list clusters (simple cli implementing the [Provider interface](https://gist.github.com/bigkevmcd/a38631d5148b1f8e8f3939aaa82aaf8f#design))
4. [ ] Create [CRD definition](https://gist.github.com/bigkevmcd/a38631d5148b1f8e8f3939aaa82aaf8f#aks-clusters)
