### ISSUE TITLE
Checklist for Deprecating GitOps Run

### ISSUE THREAD

**Issue by lasomethingsomething** [weaveworks/weave-gitops-enterprise#3514]
## Weave GitOps Enterprise/[search results](https://github.com/search?q=repo%3Aweaveworks%2Fweave-gitops-enterprise%20%22gitops%20run%22&type=code)
- [x] Remove from CLI
- [ ] Remove from API
- [x] Remove from UI
     - [x] Remove icon from UI sidebar menu
     - [x] Remove GitOps Run view
- [x] [GitOps bucket server](https://github.com/weaveworks/weave-gitops/tree/main/cmd/gitops-bucket-server)
- [x] Remove reference [here](https://github.com/weaveworks/weave-gitops-enterprise/blob/96f710f4bb1aa1efce50c8d9dd90ae68caf33027/docs/architecture/devex.md?plain=1#L15)
- [ ] Move Notifications to [Section TBD]

## Weave GitOps OSS/[search results](https://github.com/search?q=repo%3Aweaveworks%2Fweave-gitops%20%22gitops%20run%22&type=code)
- [x] Remove from CLI
- [ ] Remove from API
- [x] Remove from UI
     - [x] Remove icon from UI sidebar menu
     - [x] Remove GitOps Run view
- [x] [GitOps bucket server](https://github.com/weaveworks/weave-gitops/tree/main/cmd/gitops-bucket-server)
- [ ] Remove references from Readme

## User Docs
- [x] Remove user docs pages

## Website
- [ ] Add a "deprecated feature" notice [here](https://www.weave.works/blog/gitops-run)

## ACs
- [x] GitOps Run is gone from WGE
- [x] And gone from WeGO OSS
- [ ] And from the docs site
