### ISSUE TITLE
Extend Flux Runtime UI to Weave Gitops Runtime UI 

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#3725]
Implement the solution out of the [Weave Gitops Runtime ADR](https://github.com/weaveworks/weave-gitops-private/blob/main/docs/adrs/0026-weave-gitops-runtime-ui.md)

That involves the following:

**Weave Gitops OSS** 

https://github.com/weaveworks/weave-gitops/issues/4174

- [ ] I could configure Weave Gitops with set of labels to match controllers and crds to make visible in Flux Runtime UI
- [ ] By default, we support `flux` and `weave-gitops` labels
- [ ] Policy agent is visible in Weave Gitops Runtime for OSS (because it is supported on OSS) 
- [ ] Documented

**Weave Gitops EE**

- [ ] Using Weave Gitops Runtime from OSS 
- [ ] Weave Gitops Enterprise controllers are visible in Weave Gitops Runtime
- [ ] Documented
