### ISSUE TITLE
As a User, my clusters are still bootstrapped when they are added to the system

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#488]
The bootstrap controller currently watches for `capi/Cluster` objects transitioning to `Ready`  and then reacts by executing any ClusterBootstrapConfig jobs that match the `capi/Cluster`s labels.

`capi/Cluster` support will be extended with `gitopscluster` support so some changes will have to be made to the bootstrap controller.

**Tasks**

- [x] Bootstrap Controller watches `weave/Cluster` CRs as well as capi
- [x] Weave Cluster Controller should set the status of `weave/Cluster` CRs to Ready
- [x] Make CBC private
- [x] Re-integrate the new CBC and update acceptance tests etc
  - [x] Add RBAC to the CBC so it can watch gitopsclusters[0]
- [x] Move logic that makes sure cluster is "extra-ready" from CBC to CC
- [ ] Update docs and example templates
  - [ ] Add notes to the docs about where to add your labels now (and that they should only go on _one_ of the capi/gitops cluster CRs)

**Questions and concerns**

- Would be nice to keep the CBC backwards compatible. 
  - NO
- capi/Cluster and weave/Cluster have the opportunity to have different names? Which name is templated into the CBC? Presumably the weave/Cluster. For the first version this is fine. When we implement reflection that won't be an issue.

 [0] 

```
W0504 08:49:41.164956       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: failed to list *v1alpha1.GitopsCluster: gitopsclusters.gitops.weave.works is forbidden: User "system:serviceaccount:flux-system:cluster-bootstrap-controller" cannot list resource "gitopsclusters" in API group "gitops.weave.works" at the cluster scope
E0504 08:49:41.165000       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitopsCluster: failed to list *v1alpha1.GitopsCluster: gitopsclusters.gitops.weave.works is forbidden: User "system:serviceaccount:flux-system:cluster-bootstrap-controller" cannot list resource "gitopsclusters" in API group "gitops.weave.works" at the cluster scope
```
