### ISSUE TITLE
Show canary deployments

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#786]
## Tasks
- [x] #803
- [x] #804
- [x] #802 
- [x] #807
- [x] #805
- [x] #875
- [x] #808
- [x] #812

## Acceptance criteria
As a user, I am able to:
- [x] View a basic list of installed canaries on my clusters (no details, no linking to additional pages)
- [x] View the status of a rollout (successful/ready, progressing, failed, waiting)
- [x] View the relative status of a progressing rollout through simple fraction i.e. 1/5 based on weight for canary or iteration for blue/green & A/B
- [x] View cluster and namespace for the canary
- [x] View the target deployment for a canary
- [x] View a (truncated) status message from the canary object (re-use example from applications table)
- [x] View the last updated timestamp

Design:
<img width="1218" alt="Screenshot 2022-05-27 at 15 05 51" src="https://user-images.githubusercontent.com/19860021/170715579-c07c7b74-914f-4967-8565-a48da97bc130.png">
