### ISSUE TITLE
Show details for a canary deployment

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#832]
## Tasks
- [ ] #864 (not needed)
- [ ] #866 (not needed)
- [ ] #867 (not needed)
- [x] #868

## Acceptance criteria
As a user I am able to see within a header section:
- [x] Cluster and Namespace
- [x] Target deployment
- [x] Service
- [x] Provider
- [x] Stretch: Deployment strategy
- [ ] Stretch: application link
- [ ] Stretch: source link
- [ ] Stretch: service LINK

As a user I am able to see within a table:
- [ ] Status information returned from the Canary object

## TODO
- [ ] Determine whether any additional CRD fields are beneficial to show in our MVP - https://github.com/fluxcd/flagger/#canary-crd
- [ ] Figure out whether to link to canary service in the case of a rollout, or primary, or show both
