### ISSUE TITLE
Canary analysis tab view

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#842]
User stories:
- [x] As a user, when I view a Canary object, I can discover key information relating to how Flagger will perform the canary analysis for a new version of my application, by clicking the "Analysis" tab. See Fig 1. 
- [x] As a user, I can see which metric checks have been configured - their name, their namespace, the threshold minimum, the threshold maximum, and the interval, in a sortable-by-column table.
- [x] As a user, when seeing a metric defined using built in metrics, I would see `-` or `Not Applicable` as the namespace value as this is not applicable.
- [x] As a user, when seeing a metric defined using a custom metric template, I can discover how this is configured as the name of the metric becomes a hyperlink which when clicked, opens a modal view showing me the yaml for the relevant metric template object.
- [ ] As a user, I can see a list of configured webhooks for a given Canary object, including their name, type, timeout, Metadata (in a comma separated list of key-value pairs), and URL, in a sortable-by-column table.
- [ ] As a user, if any alerts are defined on the Canary object, I can see a list of them including their name, severity, provider name and provider namespace, in a sortable-by-column table.
- [ ] As a user, if no alerts are defined on a Canary object, I can see any configured global alerts, including their type (Slack | MS Teams) url, proxy (optional) channel, user, clusterName.
- [ ] As a user, if no alerts are defined on a Canary object AND no global alerts are configured, no Alerts table is presented to me.

Note:
- We can iteratively add tables and the hyperlink capabilities. Hence making this an epic
- We will need another API to query for AlertProviders

Design screenshots:
Fig 1. Analysis Table
<img width="1419" alt="Screenshot 2022-06-23 at 10 22 04" src="https://user-images.githubusercontent.com/19860021/175265178-6c4e3150-994b-49ff-9618-2976fce870a2.png">
Fig 2. Example modal view for a Metric Template object.
<img width="1418" alt="Screenshot 2022-06-23 at 10 22 17" src="https://user-images.githubusercontent.com/19860021/175265193-597b373b-81cc-42e2-bd47-4c26627d10d8.png">
