### ISSUE TITLE
Feature Flag

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#847]
## Tasks
- [ ] Add a feature flag (env var) `ENABLE_PROGRESSIVE_DELIVERY` to`clusters-service` to enable/disable all progressive delivery endpoints
- [ ] Add a feature flag (env var) `ENABLE_PROGRESSIVE_DELIVERY` to UI code to enable/disable Delivery section
- [ ] Make the feature flag configurable via a Helm value

## Acceptance criteria
Enable the use of the progressive delivery feature through a feature flag, configurable within the WGE helm chart.
